### ISSUE TITLE
chameleon breaks whatsapp web

### ISSUE THREAD

**Issue by WPFilmmaker** [sereneblue/chameleon#272]
# Prerequisites
- [ x] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed

## Expected Behavior
Whatsapp web (https://web.whatsapp.com/) works as usual
## Current Behavior
The site does not work and throws: "Sorry, something went wrong. We're working on getting this fixed as soon as we can."

## Relevant settings
https://privatebin.net/?024b83c0c876d30b#2sshvVmXsFbPVRAad4BExQZojjpNTxSGeACKWGxALoUP p4ss: a4f6g

## Context (Environment)
71.0 (64-bit) Firefox linux, Lubuntu 18.04.

note: the site worked fine until a few days ago...so they must have changed something  and now chameleon conflicts with it.

**Comment by sereneblue** [comment]
Hi @WPFilmmaker, did you change any settings recently? I don't use WhatsApp, but I'm sure this is a script injection issue. Can you take a look at the developer console to see if there any errors appear? If there's nothing to be found there, can you try manually toggling some of the script injection features to narrow the possible cause?

**Comment by WPFilmmaker** [comment]
@sereneblue Actually I tried disabling injection script and reload the page but it throws the same error :/
The only way to access the page is to disable chameleon (at the least so far).

I tried debugging and all I got were these errors (I tried enabling/disabling script injection): 
https://imgur.com/phCCYdl

I don't know if they are of any help-

**Comment by sereneblue** [comment]
@WPFilmmaker Thanks for testing. It seems it's an issue with the headers, rather than script injection. Can you try unchecking the `Spoof Source Referer` option?

**Comment by WPFilmmaker** [comment]
@sereneblue sorry for the late reply! I tried disabling spoof source referer but reloading nothing changes :/

This is how the page appear: https://imgur.com/gLY1l9W

**Comment by WPFilmmaker** [comment]
I tried adding the site to the whitelist and reload, but the page it is still broke unless i disable chameleon :/

**Comment by sereneblue** [comment]
Thanks for testing @WPFilmmaker. I'll find a way to test this and resolve the issue for you.

**Comment by sereneblue** [comment]
HI @WPFilmmaker,

Can you test with v0.12.25 and let me know if you're still encountering an issue. I'm curious if [this](https://github.com/sereneblue/chameleon/issues/288#issuecomment-583882526) was the cause.

**Comment by WPFilmmaker** [comment]
@sereneblue I updated and... it works! Closing this:)

**Comment by WPFilmmaker** [comment]
@sereneblue I am afraid the issue reappered :/ Any ideas?

**Comment by sereneblue** [comment]
@WPFilmmaker I don't have any ideas. There's only a few things that changed in between v0.12.25 and v0.12.26 but the changes shouldn't have affected much. I'll take another look at it again.

**Comment by WPFilmmaker** [comment]
@sereneblue  https://github.com/92lleo/WhatsappWebToGo/issues/16 same issue

**Comment by 92lleo** [comment]
Seems like whatsapp is checking features according to the given UA. I could reproduce the issue mentioned above in WhatsappWebToGo when trying with an older device. The UA I've currently set in the app is the current chrome UA. I changed it to the current Firefox UA and the issue is gone.

**Comment by WPFilmmaker** [comment]
@sereneblue is leo's adivice helpful for chameleon too? I miss using chameleon but have to keep it disabled due this error :(

**Comment by sereneblue** [comment]
@92lleo Thanks for the info.

@WPFilmmaker You should whitelist Whatsapp to use a Firefox profile. Sometimes sites do break if you use a Chrome profile (like Youtube).

**Comment by sereneblue** [comment]
@WPFilmmaker Are you experiencing an issue after whitelisting WhatsApp?

**Comment by WPFilmmaker** [comment]
@sereneblue I whitelisted whastappweb with the following settings: https://imgur.com/YH008zd
it does not help :(
if i enable chameleon, reload, whatsappweb is broken...the only way to make it work (so far) is to disable the addon.

**Comment by sereneblue** [comment]
@WPFilmmaker Hm, that's strange; the whitelist _should_ resolve this. I'll have to look into this more.

**Comment by 92lleo** [comment]
Does the whitelist work for the current tab or for the specified url only? Maybe you need to whitelist *.whatsapp.com or similar

**Comment by sereneblue** [comment]
@92lleo The whitelist works for the current tab. Chameleon doesn't support wildcards. `*.whatsapp.com` would be `whatsapp.com`. There is regex support but it requires a match on the domain first, then it filters with regular expressions (if necessary).

@WPFilmmaker Did you check `Enable whitelist`? I thought there was a bug in Chameleon when I added some sites to the whitelist to check if it was working properly, but I forgot to toggle that option. I guess I'll be removing that option in v0.20.0 because there's really isn't a need for it.

Also, instead of specifying https://web.whatsapp.com/ you should try using `whatsapp.com` instead. Please let me know if the above helps.

**Comment by WPFilmmaker** [comment]
@sereneblue whitelisting https://web.whatsapp.com/ was enough! I checked 'enable whitelist' and it wasn't toggled...toggled it, reload and it works perfectly!

I agree with you, it should be removed because IMHO if the user wants to whitelist something and sees the option to do so, it is obvious that they want "Enable whitelist" on.

**Comment by WPFilmmaker** [comment]
@sereneblue I am afraid whatsappweb is broken again..since yesterday and had to disable chameleon :( do you think something might conflict with the new version?

**Comment by sereneblue** [comment]
@WPFilmmaker Is whatsapp still whitelisted?

**Comment by WPFilmmaker** [comment]
@sereneblue yes https://web.whatsapp.com/, i saw you could add more than url in the same exception so just in case I added https://www.whatsapp.com/ as well, reloaded the page but it is still broken :(

**Comment by sereneblue** [comment]
@WPFilmmaker Did you test this with v0.20.3? That _should_ have fixed the issue with the whitelist.

**Comment by sereneblue** [comment]
@WPFilmmaker Has this issue been resolved by any recent updates?

**Comment by WPFilmmaker** [comment]
@sereneblue  I updated to 0.20.7.3 unfortunately it is still broken :/

I noticed something weird though: I put in whitelist the 2 urls above and I can see them in my white list. However if I go on the whitelist page through the icon while i am on whatsappweb it says it is not in whitelist..

Also I thought maybe having 2 sites in the same whitelist voice breaks the function, so I tried to remove one url and save but i can't! the url section becomes pink and saving does not work.

I deleted the whitelist voice and wanted to create a new one. However when I try and click save, it does not let save it.

It seems whitelisting is broken so maybe it is white whatsappweb is still broken? If you this is a bug once whitelisting works I will try again!

**Comment by sereneblue** [comment]
Thanks @WPFilmmaker,

1. This was an issue with how URLs are matched in the whitelist. Chameleon checked to see if the host (web.whatsapp.com) was equal to the domain you provided (https://web.whatsapp.com/).  This should be fixed in the next update.
2. The issue with deleting a domain and getting a validation error was probably caused by white space at the end of the textarea. This is fixed in the next update.
3. Not being allowed to save the whitelist rule was probably caused by a validation issue. I'll improve the UX so an error message is shown.

**Comment by sereneblue** [comment]
@WPFilmmaker Can you check if you're still experiencing issues with v0.20.8?

**Comment by WPFilmmaker** [comment]
@sereneblue whitelisting in v0.20.8 fixes the problem, hurray!
