### ISSUE TITLE
Font spoofing issues

### ISSUE THREAD

**Issue by h6a8ke1k** [sereneblue/chameleon#360]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior
All websites display fonts correctly, including those using remote fonts (webfonts).

## Current Behavior
Some of the websites using webfonts are not correctly displaying some icons.
For example:
[link1](https://amiunique.org/) The header bar on the top.
[link2](https://coreui.io/angular/demo/#/icons/coreui-icons) All the icons displayed on that page.
But some are displaying correctly:
[link](https://coreui.io/demo/3.1.0/#icons/coreui-icons-free.html)
Also, the links that the icons are not displaying correctly actually display the icons when page is loaded, but after a very short while (less than 1 second) the icons become some meaningless symbols. I guess it is because Chameleon changes some of the css?

## Relevant settings

Font spoofing enabled.

## Context (Environment)

Firefox 68 ESR win64

**Comment by sereneblue** [comment]
Hi @h6a8ke1k, thanks for reporting this issue. 

>  Also, the links that the icons are not displaying correctly actually display the icons when page is loaded, but after a very short while (less than 1 second) the icons become some meaningless symbols. I guess it is because Chameleon changes some of the css?

Yes, that's correct.

Icons library are slowly migrating to SVGs so web fonts should gradually become less of an issue over time. I've added a few other web fonts to a whitelist. This is fixed in v0.20.3.

**Comment by h6a8ke1k** [comment]
@sereneblue Excuse me, but I find that there are various kinds of other web fonts and it is not very likely to add all of them to the whitelist. Some of the sites are still not displaying web fonts correctly.
For example, the website [https://alternativeto.net/](https://alternativeto.net/) seems to use its own web fonts.

I discovered that if I set `browser.display.use_document_fonts` to 0, the number of fonts are reduced while web fonts are displaying correctly. Is it possible that Chameleon reduces the number of system fonts available while preserving web fonts? Thanks!

**Comment by sereneblue** [comment]
Hi @h6a8ke1k,

Thanks for commenting again on this issue. I'm experimenting with a way to handle this dynamically using `document.fonts`. It appears to work, but I'm having some trouble with the Core UI icons. I hope to have this resolved in v0.20.4.

**Comment by sereneblue** [comment]
@h6a8ke1k I've managed to find a fix that works with all of the links you listed above. This should be resolved in the next update.

**Comment by sereneblue** [comment]
@h6a8ke1k v0.20.4 has been released. ;)

**Comment by h6a8ke1k** [comment]
Thank you! I have tested and it seems to work fine.
